### ISSUE TITLE
session_start_time must be datetime object

### ISSUE THREAD

**Issue by GwydionJon** [ssciwr/mease-elabftw#22]
`pynwb` only allows `"session_start_time"` to be a datetime object, currently it is a string.
This string can be converted with  `datetime.fromisoformat(nwbfile["session_start_time"])`.

**Comment by lkeegan** [comment]
also applies to `date_of_birth`

**Comment by lkeegan** [comment]
This can be improved on the elabftw side by using type `date` for the `Subject.date_of_birth` field,
this gives a date in the form `YYYY-MM-DD`.
I've updated this mouse (which is linked from the experiment used in the tests): https://elabftw.uni-heidelberg.de/database.php?mode=view&id=534
