### ISSUE TITLE
add `get_nwb_conversion_tools_metadata()` function

### ISSUE THREAD

**Issue by lkeegan** [ssciwr/mease-elabftw#30]
There are two possible (very similar) formats for nwb `metadata` depending on use case:
- NWB file creation
  - i.e. `NWBFile(**metadata)` using the `pynwb` library
- Use with [https://github.com/catalystneuro/nwb-conversion-tools](nwb-conversion-tools)
  - This is what [mease-lab-to-nwb](https://github.com/ssciwr/mease-lab-to-nwb) will do
  - schemas:
    - https://github.com/catalystneuro/nwb-conversion-tools/blob/29bde208caf6e5a1dece80d77b9bdd0082d7ee74/src/nwb_conversion_tools/utils/json_schema.py#L205
    - https://github.com/catalystneuro/nwb-conversion-tools/blob/29bde208caf6e5a1dece80d77b9bdd0082d7ee74/src/nwb_conversion_tools/schemas/metadata_schema.json
    - `Subject` gets the schema from hdmf5: https://github.com/catalystneuro/nwb-conversion-tools/blob/29bde208caf6e5a1dece80d77b9bdd0082d7ee74/src/nwb_conversion_tools/utils/json_schema.py#L128
    - this gives the following error (and only float seems to validate as correct despite the description)
```
ValidationError: '0.02 g' is not of type 'number'

Failed validating 'type' in schema['properties']['Subject']['properties']['weight']:
    {'default': '0.02 g',
     'description': 'The weight of the subject, including units. Using '
                    'kilograms is recommended. e.g., "0.02 kg". If a float '
                    'is provided, then the weight will be stored as '
                    '"[value] kg".',
     'type': 'number'}
```
  - we have a [schema](https://github.com/ssciwr/mease-elabftw/blob/main/mease_elabftw/tests/metadata_ecephys.schema.json) in tests which looks consistent with above schemas but not with sample error message

Would be good to have `get_nwb_metadata` work for the first use case, and add `get_nwb_conversion_tools_metadata()` for the second use case. Internally it should call `get_nwb_metadata`, then make the necessary changes:
- [x] datetime objects -> strings
- [x] mouse weight -> float (in kilograms)
  - maybe it would make sense to just rescale whatever the value is to a sane mouse weight?
    - i.e. if above 1 then assume unit is grams & divide by 1000
    - I'll ask about this
- [x] ...?

**Comment by GwydionJon** [comment]
I might have found a way to convert the pynwb file back into a dict:

 ```
nwbfile_dict = nwb_metadata.get("NWBFile")
subject_dict = nwb_metadata.get("Subject")
{key: pynwb_file.fields[key] for key in nwbfile_dict}
{key: pynwb_file_1.subject.fields[key] for key in subject_dict}
```
